import PDFDocument from "pdfkit";

const COLORS = {
  title: "#111827",
  subtitle: "#6B7280",
  heading: "#111827",
  body: "#374151",
  accent: "#6366F1",
  footer: "#9CA3AF",
  rule: "#E5E7EB",
};

const normalizeSpaces = (value) =>
  String(value ?? "").replace(/\s+/g, " ").trim();

const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const margin = 48;
      const title = normalizeSpaces(data.title) || "Document";
      const subtitle = normalizeSpaces(data.subtitle);
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: margin, bottom: 56, left: margin, right: margin },
        bufferPages: true,
        info: {
          Author: "Nexora AI",
          Title: title,
          Creator: "Nexora AI",
        },
      });

      const chunks = [];
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;
      const contentWidth = pageWidth - margin * 2;
      const bottomSafe = pageHeight - 64;

      // Title
      doc
        .font("Helvetica-Bold")
        .fontSize(20)
        .fillColor(COLORS.title)
        .text(title, {
          width: contentWidth,
          lineGap: 1,
        });

      // Accent rule under title
      const ruleY = doc.y + 4;
      doc
        .strokeColor(COLORS.accent)
        .lineWidth(1.5)
        .moveTo(margin, ruleY)
        .lineTo(margin + 48, ruleY)
        .stroke();
      doc.y = ruleY + 8;

      // Subtitle
      if (subtitle) {
        doc
          .font("Helvetica")
          .fontSize(10)
          .fillColor(COLORS.subtitle)
          .text(subtitle, {
            width: contentWidth,
            lineGap: 1,
          });
        doc.moveDown(0.7);
      } else {
        doc.moveDown(0.45);
      }

      const ensureSpace = (needed = 36) => {
        if (doc.y + needed > bottomSafe) {
          doc.addPage();
        }
      };

      const sections = Array.isArray(data?.sections) ? data.sections : [];
      sections.forEach((section, index) => {
        const heading =
          normalizeSpaces(section.heading || section.title) ||
          `Section ${index + 1}`;
        const points = (Array.isArray(section.points) ? section.points : [])
          .map((point) => normalizeSpaces(point))
          .filter(Boolean);

        ensureSpace(40);

        doc
          .font("Helvetica-Bold")
          .fontSize(12)
          .fillColor(COLORS.heading)
          .text(heading, {
            width: contentWidth,
            lineGap: 1,
          });

        doc.moveDown(0.25);

        if (points.length) {
          ensureSpace(28);
          doc
            .font("Helvetica")
            .fontSize(10)
            .fillColor(COLORS.body)
            .list(points, {
              width: contentWidth,
              bulletRadius: 1.5,
              textIndent: 12,
              bulletIndent: 0,
              lineGap: 1,
              paragraphGap: 3,
            });
        }

        doc.moveDown(0.55);
      });

      // Footers on every page
      const range = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i += 1) {
        doc.switchToPage(range.start + i);
        const savedBottom = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;

        const bottom = pageHeight - 32;

        doc
          .strokeColor(COLORS.rule)
          .lineWidth(0.5)
          .moveTo(margin, bottom - 10)
          .lineTo(pageWidth - margin, bottom - 10)
          .stroke();

        doc
          .font("Helvetica")
          .fontSize(8)
          .fillColor(COLORS.footer)
          .text("Generated by Nexora AI", margin, bottom - 2, {
            width: contentWidth / 2,
            align: "left",
            lineBreak: false,
          });

        doc
          .font("Helvetica")
          .fontSize(8)
          .fillColor(COLORS.footer)
          .text(`${i + 1}`, margin + contentWidth / 2, bottom - 2, {
            width: contentWidth / 2,
            align: "right",
            lineBreak: false,
          });

        doc.page.margins.bottom = savedBottom;
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export default generatePdf;
