import pptxgen from "pptxgenjs";

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B",
  };

export const generatePPT = async(data) => {
    const ppt = new pptxgen();
    ppt.layout = "LAYOUT_WIDE";
    ppt.author = "NexoraAI"
    ppt.title = data.title;
    ppt.subject = data.title;
    ppt.company = "NexoraAI";
    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
    }
    
    addCover(ppt, data)

    data?.slides?.forEach((s, idx) => {
        addContentSlide(
            ppt,
            s.title,
            s.points,
            idx + 1,
            data?.slides?.length,
        )  
    });

    addThankyou(ppt)

    return ppt

}


const addCover = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.background = {
        color: COLORS.primary,
    }
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: "60A5FA",
        },
        line:{
            color: "60A5FA"
        }
    })

    slide.addText(data.title, {
        x: 1,
        y: 2,
        w: 11.3,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28,
    });

    slide.addText(data.subtitle, {
        x: 1,
        y: 2.8,
        w: 11.5,
        h: 0.4,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28
    })

    slide.addText("Generated By NexoraAI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE",
        fontSize: 10,
    })

}   


const addContentSlide = (ppt,title,points,page,total)=>{
    const slide = ppt.addSlide();
    slide.background = {
        color: COLORS.white,
    }

    slide.addText(title, {
        x: 0.6,
        y: 0.35,
        w: 10,
        h: 0.4,
        fontSize: 24,
        bold: true,
        color: COLORS.primary,
    })

    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.85,
        w: 12,
        h: 0,
        line:{
            color: COLORS.border,
            width: 1.2,
        },
    })

    const visiblePoints = points.slice(0,6)


    visiblePoints.forEach((points,index)=>{
        const y = 1.2 + index*0.75

        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.58,
            fill:{
                color: index % 2 ? "F8FAFC" : "EFF6FF",
            },
            line:{
                color: COLORS.border,
                width: 1.2,
            },
            radius: 0.08,
        })

        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.92,
            y: y + 0.18,
            w: 0.12,
            h: 0.12,
            fill:{
                color: COLORS.primary,
            },
            line:{
                color: COLORS.primary,
            },
        })

        slide.addText(points, {
            x: 1.2,
            y: y + 0.03,
            w: 11,
            h: 0.13,
            fontSize: 15,
            color: COLORS.text,
            fit: "shrink"
        })

    })
    slide.addText(`${page}/${total}`, {
        x: 12.1,
        y: 6.9,
        w: 0.8,
        h: 0.2,
        align: "right",
        fontSize: 10,
        color: COLORS.muted,
    })


    slide.addText(`NexoraAI`, {
        x: 0.6,
        y: 6.9,
        w: 2,
        h: 0.2,
        fontSize: 10,
        color: COLORS.muted,
    })
}

const addThankyou = (ppt) =>{
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary,
    }

    slide.addText(`Thank you`, {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 34,
        bold: true,
    });

    slide.addText(`Generated By NexoraAI`, {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    });

}